use std::path::PathBuf;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn ordinary_source_imports_standard_authority_and_keeps_roles_empty() {
    let source = signal_mirror::MIRROR_INTERFACE_SOURCE;
    assert!(source.starts_with("Interface.{1 0 0}\n[signal_standard:lib.["));
    assert!(source.contains("ObjectDigest"));
    assert!(source.contains("StandardSocket"));
    assert!(source.contains("MirrorRequest.["));
    assert!(source.contains("MirrorReply.["));
    assert!(source.contains("\n  []\n  []\n  []\n  ["));
    assert!(source.contains("PayloadBytes.Vector<Integer>"));
    assert!(source.contains("ArtifactBytes.Vector<Integer>"));

    for copied in [
        concat!("Entry", "Digest."),
        concat!("Artifact", "Digest."),
        concat!("Mirror", "Address."),
        concat!("\n    ", "Bytes."),
        concat!("Fixed", "Bytes."),
    ] {
        assert!(
            !source.contains(copied),
            "retired declaration remains: {copied}"
        );
    }
}

#[test]
fn strict_projection_uses_encoded_local_and_imported_coordinates() {
    let generated = signal_mirror::MIRROR_INTERFACE_RUST;
    assert!(generated.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    for visible in ["MirrorRequest", "MirrorReply", "EntryEnvelope"] {
        assert!(!generated.contains(&format!("pub enum {visible}")));
        assert!(!generated.contains(&format!("pub struct {visible}")));
    }
    assert!(generated.contains("signal_standard::schema::lib::z"));
    assert_eq!(
        signal_mirror::bootstrap_manifest::DECLARATION_SEATS.len(),
        57
    );
}

#[test]
fn strict_interface_is_the_sole_mirror_schema_authority() {
    let root = root();
    assert!(!root.join("schema").exists());
    assert!(root.join("ethos/interface.ethos").is_file());
    assert_eq!(
        signal_mirror::MIRROR_INTERFACE_SOURCE,
        include_str!("../ethos/interface.ethos")
    );
}
