// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2Vcs2 {z2VWLf , z2VLE1 ,} 
pub struct z2VaxY {
    pub field_0: z2Ve8p,
    pub field_1: z2VcqM,
}
pub enum z2VcyE {z2VcFn , z2VPd1 , z2VZT1 , z2VRBT , z2VQma ,} 
pub struct z2VbvA ( z2Ve8p ,) ;
pub struct z2VbBN {
    pub field_0: z2Ve8p,
    pub field_1: z2VPgu,
}
pub struct z2VYSu {
    pub field_0: z2Ve8p,
    pub field_1: z2VTXE,
    pub field_2: Vec<z2VPuU>,
}
pub enum z2VVny {z2VVjQ ( z2VTq5 ,) , z2VaYk ( z2VZWt ,) , z2VNu6 ( z2VTXE ,) , z2VZ8E ( z2Vdqa ,) , z2VdHF ( z2VbvA ,) ,} 
pub struct z2VZWt {
    pub field_0: z2Ve8p,
    pub field_1: z2VcqM,
    pub field_2: Option<signal_standard::schema::lib::z2VduW>,
}
pub struct z2VWFj {
    pub field_0: z2Ve8p,
    pub field_1: z2VcqM,
}
pub struct z2VLxP {
    pub field_0: z2Ve8p,
    pub field_1: z2VUKn,
    pub field_2: z2VSAK,
}
pub enum z2VPgu {z2VXM2 , z2Vf1c ,} 
pub struct z2Vbm6 {
    pub field_0: z2Ve8p,
    pub field_1: Option<z2VcqM>,
}
pub struct z2VUxk(Vec<u64>);
impl z2VUxk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<u64>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<u64> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<u64> {
        self.0
    }
}
pub struct z2VMCw(std::string::String);
impl z2VMCw {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VTq5 {
    pub field_0: z2Ve8p,
    pub field_1: Option<z2VcqM>,
    pub field_2: Vec<z2VPuU>,
}
pub struct z2VUwg(Vec<u64>);
impl z2VUwg {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<u64>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<u64> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<u64> {
        self.0
    }
}
pub struct z2VUKn(u64);
impl z2VUKn {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VcqM {
    pub field_0: z2VSAK,
    pub field_1: signal_standard::schema::lib::z2VSyM,
}
pub struct z2VPuU {
    pub field_0: z2VSAK,
    pub field_1: Option<signal_standard::schema::lib::z2VSyM>,
    pub field_2: signal_standard::schema::lib::z2VSyM,
    pub field_3: z2VUwg,
}
pub struct z2Vdqa(Option<z2Ve8p>);
impl z2Vdqa {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Option<z2Ve8p>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Option<z2Ve8p> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Option<z2Ve8p> {
        self.0
    }
}
pub struct z2VUTH {
    pub field_0: z2Ve8p,
    pub field_1: z2VcyE,
    pub field_2: Option<z2VcqM>,
}
pub struct z2VbP4 {
    pub field_0: z2Ve8p,
    pub field_1: z2Vcs2,
}
pub enum z2VTqL {z2VLCz ( z2VbBN ,) , z2VMR1 ( z2VY7x ,) , z2VWHb ( z2VbP4 ,) , z2VR8x ( z2VWFj ,) , z2VPpj ( z2Vc3D ,) , z2VSxB ( z2VQTe ,) , z2VXSq ( z2VaxY ,) , z2VaSa ( z2VLxP ,) , z2VVve ( z2VYSu ,) , z2VX2Y ( z2VUTH ,) ,} 
pub struct z2Ve8p(std::string::String);
impl z2Ve8p {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VQTe {
    pub field_0: z2Ve8p,
    pub field_1: z2VdLR,
    pub field_2: Option<z2VcqM>,
}
pub struct z2VTXE {
    pub field_0: z2Ve8p,
    pub field_1: z2VUKn,
    pub field_2: z2VSAK,
    pub field_3: signal_standard::schema::lib::z2VSyM,
    pub field_4: z2VUxk,
}
pub enum z2VdLR {z2VZJ4 , z2VXhC , z2VLZN ,} 
pub struct z2VSAK(u64);
impl z2VSAK {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VY7x {
    pub field_0: Vec<z2Vbm6>,
}
pub struct z2Vc3D ( z2VMCw ,) ;
