// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
)]
pub struct Bytes(nota_next::ByteSequence);
#[rustfmt::skip]
impl Bytes {
    pub fn new(payload: Vec<u8>) -> Self {
        Self(nota_next::ByteSequence::new(payload))
    }
    pub fn payload(&self) -> &[u8] {
        self.0.payload()
    }
    pub fn into_payload(self) -> Vec<u8> {
        self.0.into_payload()
    }
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
)]
pub struct FixedBytes<const WIDTH: usize>(nota_next::FixedByteSequence<WIDTH>);
#[rustfmt::skip]
impl<const WIDTH: usize> FixedBytes<WIDTH> {
    pub fn new(payload: [u8; WIDTH]) -> Self {
        Self(nota_next::FixedByteSequence::new(payload))
    }
    pub fn payload(&self) -> &[u8; WIDTH] {
        self.0.payload()
    }
    pub fn into_payload(self) -> [u8; WIDTH] {
        self.0.into_payload()
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoreName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckpointSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntryDigest(FixedBytes<32>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArtifactDigest(FixedBytes<32>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PayloadBytes(Bytes);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArtifactBytes(Bytes);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HeadMark {
    pub sequence: CommitSequence,
    pub digest: EntryDigest,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct PreviousDigest(Option<EntryDigest>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntryEnvelope {
    pub sequence: CommitSequence,
    pub(crate) previous_digest: PreviousDigest,
    pub digest: EntryDigest,
    pub payload: PayloadBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ExpectedHead(Option<HeadMark>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Entries(Vec<EntryEnvelope>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntrySuffix {
    pub store: StoreName,
    pub(crate) expected_head: ExpectedHead,
    pub(crate) entries: Entries,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppendReceipt {
    pub store: StoreName,
    pub head: HeadMark,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AppendRejectionReason {
    UnknownStore,
    SequenceGap,
    HeadForked,
    DigestMismatch,
    EmptySuffix,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct AppendRejectionHead(Option<HeadMark>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppendRejection {
    pub store: StoreName,
    pub reason: AppendRejectionReason,
    pub(crate) append_rejection_head: AppendRejectionHead,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckpointArtifact {
    pub store: StoreName,
    pub sequence: CheckpointSequence,
    pub covered_end: CommitSequence,
    pub digest: ArtifactDigest,
    pub artifact: ArtifactBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckpointReceipt {
    pub store: StoreName,
    pub sequence: CheckpointSequence,
    pub covered_end: CommitSequence,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PublishRejectionReason {
    UnknownStore,
    CoverageRegressed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PublishRejection {
    pub store: StoreName,
    pub reason: PublishRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MirrorAddress(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Source(Option<MirrorAddress>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObjectNotice {
    pub store: StoreName,
    pub head: HeadMark,
    pub(crate) source: Source,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObjectNoticeReceipt {
    pub store: StoreName,
    pub head: HeadMark,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectNoticeRejectionReason {
    UnknownStore,
    SourceUnavailable,
    HeadBehind,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ObjectNoticeRejectionHead(Option<HeadMark>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObjectNoticeRejection {
    pub store: StoreName,
    pub reason: ObjectNoticeRejectionReason,
    pub(crate) object_notice_rejection_head: ObjectNoticeRejectionHead,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RestoreQuery(StoreName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Suffix(Vec<EntryEnvelope>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RestoreBundle {
    pub store: StoreName,
    pub checkpoint: CheckpointArtifact,
    pub(crate) suffix: Suffix,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RestoreRejectionReason {
    UnknownStore,
    NoCheckpoint,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RestoreRejection {
    pub store: StoreName,
    pub reason: RestoreRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FaultDetail(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FaultReport(FaultDetail);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HeadQuery(Option<StoreName>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct StoreHeadMark(Option<HeadMark>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoreHead {
    pub store: StoreName,
    pub(crate) store_head_mark: StoreHeadMark,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Heads(Vec<StoreHead>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HeadListing(Heads);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Append(EntrySuffix),
    PublishCheckpoint(CheckpointArtifact),
    NotifyObject(ObjectNotice),
    Restore(RestoreQuery),
    ObserveHeads(HeadQuery),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Appended(AppendReceipt),
    AppendRejected(AppendRejection),
    CheckpointPublished(CheckpointReceipt),
    PublishRejected(PublishRejection),
    ObjectNoticeAccepted(ObjectNoticeReceipt),
    ObjectNoticeRejected(ObjectNoticeRejection),
    Restored(RestoreBundle),
    RestoreRejected(RestoreRejection),
    HeadsObserved(HeadListing),
    MirrorFaulted(FaultReport),
}

#[rustfmt::skip]
impl StoreName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for StoreName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for StoreName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for StoreName {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for StoreName {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl CommitSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CommitSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for CommitSequence {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl PartialEq<u64> for CommitSequence {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}
#[rustfmt::skip]
impl PartialOrd<u64> for CommitSequence {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl CheckpointSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CheckpointSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for CheckpointSequence {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl PartialEq<u64> for CheckpointSequence {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}
#[rustfmt::skip]
impl PartialOrd<u64> for CheckpointSequence {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl EntryDigest {
    pub fn new(payload: FixedBytes<32>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &FixedBytes<32> {
        &self.0
    }
    pub fn into_payload(self) -> FixedBytes<32> {
        self.0
    }
}
#[rustfmt::skip]
impl From<FixedBytes<32>> for EntryDigest {
    fn from(payload: FixedBytes<32>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ArtifactDigest {
    pub fn new(payload: FixedBytes<32>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &FixedBytes<32> {
        &self.0
    }
    pub fn into_payload(self) -> FixedBytes<32> {
        self.0
    }
}
#[rustfmt::skip]
impl From<FixedBytes<32>> for ArtifactDigest {
    fn from(payload: FixedBytes<32>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PayloadBytes {
    pub fn new(payload: Bytes) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Bytes {
        &self.0
    }
    pub fn into_payload(self) -> Bytes {
        self.0
    }
}
#[rustfmt::skip]
impl From<Bytes> for PayloadBytes {
    fn from(payload: Bytes) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ArtifactBytes {
    pub fn new(payload: Bytes) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Bytes {
        &self.0
    }
    pub fn into_payload(self) -> Bytes {
        self.0
    }
}
#[rustfmt::skip]
impl From<Bytes> for ArtifactBytes {
    fn from(payload: Bytes) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PreviousDigest {
    pub fn new(payload: Option<EntryDigest>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<EntryDigest> {
        &self.0
    }
    pub fn into_payload(self) -> Option<EntryDigest> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<EntryDigest>> for PreviousDigest {
    fn from(payload: Option<EntryDigest>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExpectedHead {
    pub fn new(payload: Option<HeadMark>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadMark> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadMark> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadMark>> for ExpectedHead {
    fn from(payload: Option<HeadMark>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Entries {
    pub fn new(payload: Vec<EntryEnvelope>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EntryEnvelope> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EntryEnvelope> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EntryEnvelope>> for Entries {
    fn from(payload: Vec<EntryEnvelope>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AppendRejectionHead {
    pub fn new(payload: Option<HeadMark>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadMark> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadMark> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadMark>> for AppendRejectionHead {
    fn from(payload: Option<HeadMark>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MirrorAddress {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MirrorAddress {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for MirrorAddress {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for MirrorAddress {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for MirrorAddress {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl Source {
    pub fn new(payload: Option<MirrorAddress>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<MirrorAddress> {
        &self.0
    }
    pub fn into_payload(self) -> Option<MirrorAddress> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<MirrorAddress>> for Source {
    fn from(payload: Option<MirrorAddress>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObjectNoticeRejectionHead {
    pub fn new(payload: Option<HeadMark>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadMark> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadMark> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadMark>> for ObjectNoticeRejectionHead {
    fn from(payload: Option<HeadMark>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RestoreQuery {
    pub fn new(payload: StoreName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreName {
        &self.0
    }
    pub fn into_payload(self) -> StoreName {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreName> for RestoreQuery {
    fn from(payload: StoreName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Suffix {
    pub fn new(payload: Vec<EntryEnvelope>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EntryEnvelope> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EntryEnvelope> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EntryEnvelope>> for Suffix {
    fn from(payload: Vec<EntryEnvelope>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FaultDetail {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FaultDetail {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for FaultDetail {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for FaultDetail {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for FaultDetail {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl FaultReport {
    pub fn new(payload: FaultDetail) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &FaultDetail {
        &self.0
    }
    pub fn into_payload(self) -> FaultDetail {
        self.0
    }
}
#[rustfmt::skip]
impl From<FaultDetail> for FaultReport {
    fn from(payload: FaultDetail) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HeadQuery {
    pub fn new(payload: Option<StoreName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<StoreName> {
        &self.0
    }
    pub fn into_payload(self) -> Option<StoreName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<StoreName>> for HeadQuery {
    fn from(payload: Option<StoreName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoreHeadMark {
    pub fn new(payload: Option<HeadMark>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadMark> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadMark> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadMark>> for StoreHeadMark {
    fn from(payload: Option<HeadMark>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Heads {
    pub fn new(payload: Vec<StoreHead>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<StoreHead> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<StoreHead> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<StoreHead>> for Heads {
    fn from(payload: Vec<StoreHead>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HeadListing {
    pub fn new(payload: Heads) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Heads {
        &self.0
    }
    pub fn into_payload(self) -> Heads {
        self.0
    }
}
#[rustfmt::skip]
impl From<Heads> for HeadListing {
    fn from(payload: Heads) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn append(payload: EntrySuffix) -> Self {
        Self::Append(payload)
    }
    pub fn publish_checkpoint(payload: CheckpointArtifact) -> Self {
        Self::PublishCheckpoint(payload)
    }
    pub fn notify_object(payload: ObjectNotice) -> Self {
        Self::NotifyObject(payload)
    }
    pub fn restore(payload: StoreName) -> Self {
        Self::Restore(RestoreQuery::new(payload))
    }
    pub fn observe_heads(payload: Option<StoreName>) -> Self {
        Self::ObserveHeads(HeadQuery::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn appended(payload: AppendReceipt) -> Self {
        Self::Appended(payload)
    }
    pub fn append_rejected(payload: AppendRejection) -> Self {
        Self::AppendRejected(payload)
    }
    pub fn checkpoint_published(payload: CheckpointReceipt) -> Self {
        Self::CheckpointPublished(payload)
    }
    pub fn publish_rejected(payload: PublishRejection) -> Self {
        Self::PublishRejected(payload)
    }
    pub fn object_notice_accepted(payload: ObjectNoticeReceipt) -> Self {
        Self::ObjectNoticeAccepted(payload)
    }
    pub fn object_notice_rejected(payload: ObjectNoticeRejection) -> Self {
        Self::ObjectNoticeRejected(payload)
    }
    pub fn restored(payload: RestoreBundle) -> Self {
        Self::Restored(payload)
    }
    pub fn restore_rejected(payload: RestoreRejection) -> Self {
        Self::RestoreRejected(payload)
    }
    pub fn heads_observed(payload: Heads) -> Self {
        Self::HeadsObserved(HeadListing::new(payload))
    }
    pub fn mirror_faulted(payload: FaultDetail) -> Self {
        Self::MirrorFaulted(FaultReport::new(payload))
    }
}

#[rustfmt::skip]
impl From<EntrySuffix> for Input {
    fn from(payload: EntrySuffix) -> Self {
        Self::Append(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointArtifact> for Input {
    fn from(payload: CheckpointArtifact) -> Self {
        Self::PublishCheckpoint(payload)
    }
}

#[rustfmt::skip]
impl From<ObjectNotice> for Input {
    fn from(payload: ObjectNotice) -> Self {
        Self::NotifyObject(payload)
    }
}

#[rustfmt::skip]
impl From<RestoreQuery> for Input {
    fn from(payload: RestoreQuery) -> Self {
        Self::Restore(payload)
    }
}

#[rustfmt::skip]
impl From<HeadQuery> for Input {
    fn from(payload: HeadQuery) -> Self {
        Self::ObserveHeads(payload)
    }
}

#[rustfmt::skip]
impl From<AppendReceipt> for Output {
    fn from(payload: AppendReceipt) -> Self {
        Self::Appended(payload)
    }
}

#[rustfmt::skip]
impl From<AppendRejection> for Output {
    fn from(payload: AppendRejection) -> Self {
        Self::AppendRejected(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointReceipt> for Output {
    fn from(payload: CheckpointReceipt) -> Self {
        Self::CheckpointPublished(payload)
    }
}

#[rustfmt::skip]
impl From<PublishRejection> for Output {
    fn from(payload: PublishRejection) -> Self {
        Self::PublishRejected(payload)
    }
}

#[rustfmt::skip]
impl From<ObjectNoticeReceipt> for Output {
    fn from(payload: ObjectNoticeReceipt) -> Self {
        Self::ObjectNoticeAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<ObjectNoticeRejection> for Output {
    fn from(payload: ObjectNoticeRejection) -> Self {
        Self::ObjectNoticeRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RestoreBundle> for Output {
    fn from(payload: RestoreBundle) -> Self {
        Self::Restored(payload)
    }
}

#[rustfmt::skip]
impl From<RestoreRejection> for Output {
    fn from(payload: RestoreRejection) -> Self {
        Self::RestoreRejected(payload)
    }
}

#[rustfmt::skip]
impl From<HeadListing> for Output {
    fn from(payload: HeadListing) -> Self {
        Self::HeadsObserved(payload)
    }
}

#[rustfmt::skip]
impl From<FaultReport> for Output {
    fn from(payload: FaultReport) -> Self {
        Self::MirrorFaulted(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_APPEND: u64 = 0x0000000000000000;
    pub const INPUT_PUBLISH_CHECKPOINT: u64 = 0x0001000000000000;
    pub const INPUT_NOTIFY_OBJECT: u64 = 0x0002000000000000;
    pub const INPUT_RESTORE: u64 = 0x0003000000000000;
    pub const INPUT_OBSERVE_HEADS: u64 = 0x0004000000000000;
    pub const OUTPUT_APPENDED: u64 = 0x0100000000000000;
    pub const OUTPUT_APPEND_REJECTED: u64 = 0x0101000000000000;
    pub const OUTPUT_CHECKPOINT_PUBLISHED: u64 = 0x0102000000000000;
    pub const OUTPUT_PUBLISH_REJECTED: u64 = 0x0103000000000000;
    pub const OUTPUT_OBJECT_NOTICE_ACCEPTED: u64 = 0x0104000000000000;
    pub const OUTPUT_OBJECT_NOTICE_REJECTED: u64 = 0x0105000000000000;
    pub const OUTPUT_RESTORED: u64 = 0x0106000000000000;
    pub const OUTPUT_RESTORE_REJECTED: u64 = 0x0107000000000000;
    pub const OUTPUT_HEADS_OBSERVED: u64 = 0x0108000000000000;
    pub const OUTPUT_MIRROR_FAULTED: u64 = 0x0109000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Append,
    PublishCheckpoint,
    NotifyObject,
    Restore,
    ObserveHeads,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Appended,
    AppendRejected,
    CheckpointPublished,
    PublishRejected,
    ObjectNoticeAccepted,
    ObjectNoticeRejected,
    Restored,
    RestoreRejected,
    HeadsObserved,
    MirrorFaulted,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Append(_) => InputRoute::Append,
            Self::PublishCheckpoint(_) => InputRoute::PublishCheckpoint,
            Self::NotifyObject(_) => InputRoute::NotifyObject,
            Self::Restore(_) => InputRoute::Restore,
            Self::ObserveHeads(_) => InputRoute::ObserveHeads,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Append(_) => short_header::INPUT_APPEND,
            Self::PublishCheckpoint(_) => short_header::INPUT_PUBLISH_CHECKPOINT,
            Self::NotifyObject(_) => short_header::INPUT_NOTIFY_OBJECT,
            Self::Restore(_) => short_header::INPUT_RESTORE,
            Self::ObserveHeads(_) => short_header::INPUT_OBSERVE_HEADS,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_APPEND => Ok(InputRoute::Append),
            short_header::INPUT_PUBLISH_CHECKPOINT => Ok(InputRoute::PublishCheckpoint),
            short_header::INPUT_NOTIFY_OBJECT => Ok(InputRoute::NotifyObject),
            short_header::INPUT_RESTORE => Ok(InputRoute::Restore),
            short_header::INPUT_OBSERVE_HEADS => Ok(InputRoute::ObserveHeads),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Appended(_) => OutputRoute::Appended,
            Self::AppendRejected(_) => OutputRoute::AppendRejected,
            Self::CheckpointPublished(_) => OutputRoute::CheckpointPublished,
            Self::PublishRejected(_) => OutputRoute::PublishRejected,
            Self::ObjectNoticeAccepted(_) => OutputRoute::ObjectNoticeAccepted,
            Self::ObjectNoticeRejected(_) => OutputRoute::ObjectNoticeRejected,
            Self::Restored(_) => OutputRoute::Restored,
            Self::RestoreRejected(_) => OutputRoute::RestoreRejected,
            Self::HeadsObserved(_) => OutputRoute::HeadsObserved,
            Self::MirrorFaulted(_) => OutputRoute::MirrorFaulted,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Appended(_) => short_header::OUTPUT_APPENDED,
            Self::AppendRejected(_) => short_header::OUTPUT_APPEND_REJECTED,
            Self::CheckpointPublished(_) => short_header::OUTPUT_CHECKPOINT_PUBLISHED,
            Self::PublishRejected(_) => short_header::OUTPUT_PUBLISH_REJECTED,
            Self::ObjectNoticeAccepted(_) => short_header::OUTPUT_OBJECT_NOTICE_ACCEPTED,
            Self::ObjectNoticeRejected(_) => short_header::OUTPUT_OBJECT_NOTICE_REJECTED,
            Self::Restored(_) => short_header::OUTPUT_RESTORED,
            Self::RestoreRejected(_) => short_header::OUTPUT_RESTORE_REJECTED,
            Self::HeadsObserved(_) => short_header::OUTPUT_HEADS_OBSERVED,
            Self::MirrorFaulted(_) => short_header::OUTPUT_MIRROR_FAULTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_APPENDED => Ok(OutputRoute::Appended),
            short_header::OUTPUT_APPEND_REJECTED => Ok(OutputRoute::AppendRejected),
            short_header::OUTPUT_CHECKPOINT_PUBLISHED => {
                Ok(OutputRoute::CheckpointPublished)
            }
            short_header::OUTPUT_PUBLISH_REJECTED => Ok(OutputRoute::PublishRejected),
            short_header::OUTPUT_OBJECT_NOTICE_ACCEPTED => {
                Ok(OutputRoute::ObjectNoticeAccepted)
            }
            short_header::OUTPUT_OBJECT_NOTICE_REJECTED => {
                Ok(OutputRoute::ObjectNoticeRejected)
            }
            short_header::OUTPUT_RESTORED => Ok(OutputRoute::Restored),
            short_header::OUTPUT_RESTORE_REJECTED => Ok(OutputRoute::RestoreRejected),
            short_header::OUTPUT_HEADS_OBSERVED => Ok(OutputRoute::HeadsObserved),
            short_header::OUTPUT_MIRROR_FAULTED => Ok(OutputRoute::MirrorFaulted),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Append",
        "PublishCheckpoint",
        "NotifyObject",
        "Restore",
        "ObserveHeads",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
